FROM python:3.9.1

RUN apt-get install wget
# dependence for psycopg2
RUN apt-get install libpq-dev
RUN pip install pandas psycopg2 sqlalchemy

WORKDIR /app
COPY ingest_data.py ingest_data.py

ENTRYPOINT [ "python", "ingest_data.py" ]